/**
 * External adapter to get weather data from Coinapi.
 *
 * @description This adapter fetches data from coinapi.
 * @node_identifier 
 * @platforms Docker, AWS Lambda, GCP Functions
 * @data_sources
 *   
 */



name: Coinapi External Adapter
description: An external adapter to get eth/usd
node_identifier: coinapi_cl_ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: coinapi
    url: https://coinapi.io/
parameters:
  - base
