/**
 * External adapter to get weather data from OpenWeatherMap.
 *
 * @description This adapter fetches weather data from OpenWeatherMap for a specified city.
 * @node_identifier openweathermap_cl_ea
 * @platforms Docker, AWS Lambda, GCP Functions
 * @data_sources
 *   - name: OpenWeatherMap
 *     url: https://openweathermap.org/
 * @parameters
 *   - city: The name of the city for which to fetch weather data.
 */



name: OpenWeatherMap External Adapter
description: An external adapter to get the weather
node_identifier: openweathermap_cl_ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: OpenWeatherMap
    url: https://openweathermap.org/
parameters:
  - city